name: Build and Push Docker Image

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV
        id: extract_branch

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/rjskudra/irs_php:${{ env.BRANCH_NAME }}
            ${{ github.ref == 'refs/heads/main' && 'ghcr.io/rjskudra/irs_php:latest' || '' }}
          # Added cache configuration for better performance
          cache-from: type=gha
          cache-to: type=gha,mode=max